name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install
        run: npm ci --no-audit --platform=linux

      - name: Install Coveralls
        run: npm install -g coveralls

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Upload Coverage to Coveralls
        run: npm run coveralls
